# Generated by Django 5.0 on 2023-12-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEmployes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
