# Generated by Django 5.0 on 2023-12-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInformations',
            fields=[
                ('hotel_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('hotel_city', models.CharField(max_length=255)),
                ('hotel_country', models.CharField(max_length=255)),
                ('hotel_total_employee', models.PositiveIntegerField()),
                ('hotel_creation_date', models.DateField()),
            ],
        ),
    ]
