# Generated by Django 5.0 on 2023-12-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUtilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
