# Generated by Django 5.0 on 2023-12-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEmployes', '0003_remove_employee_user'),
        ('GestionUtilisateurs', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionEmployes.employee'),
        ),
    ]
